Models/ErrorViewModel.cs
namespace ProyectoEntityFramework.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Usuarios.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoEntityFramework.Models
{
    public class Usuarios
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdUsuario { get; set; }

        [Required, StringLength(255)]
        public string Nombre { get; set; }

        [Required, StringLength(255)]
        public string Correo { get; set; }

        [Required, StringLength(10)]
        public string Telefono { get; set; }

        [Required, StringLength(255)]
        public string Direccion { get; set; }
    }
}

Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoEntityFramework.Contexto;
using ProyectoEntityFramework.Models;
using System.Diagnostics;

namespace ProyectoEntityFramework.Controllers
{
    public class InicioController : Controller
    {
        // Inyectamos una instancia de MyDbContext
        private readonly MyDbContext _contexto;

        public InicioController(MyDbContext contexto)
        {
            _contexto = contexto;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // Consulta para listar los usuarios de la BD
            var usuarios = await (from usuario in _contexto.Usuarios
                                  select usuario).ToListAsync();
            return View(usuarios);
        }
        
        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        // Crear usuario
        [HttpPost]
        public async Task<IActionResult> Crear(Usuarios usuarios)
        {
            if (usuarios != null)
            {
                _contexto.Usuarios.Add(usuarios);
                await _contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            } 

            return View();  
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = _contexto.Usuarios.Find(id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // Editar usuario
        [HttpPost]
        public async Task<IActionResult> Editar(Usuarios usuarios)
        {
            if (usuarios != null)
            {
                _contexto.Update(usuarios);
                await _contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = _contexto.Usuarios.Find(id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // Eliminar usuario
        [HttpPost, ActionName("Eliminar")]
        public async Task<IActionResult> EliminarUsuario(int? id)
        {
            var usuario = await _contexto.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return View();
            }

            _contexto.Usuarios.Remove(usuario);
            await _contexto.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/Inicio/Crear.cshtml
@model ProyectoEntityFramework.Models.Usuarios

@{
    ViewData["Title"] = "Crear usuario";
}

<div class="text-center">
    <h2 class="display-4">Crear un nuevo usuario</h2>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-secondary">
                <p class="text-white">Crear usuarios</p>
            </div>
            <div class="card body">
                <form asp-action="Crear" method="post" class="p-2">
                    <input class="form-control mb-2" type="text" placeholder="Nombre" asp-for="Nombre" required />
                    <input class="form-control mb-2" type="email" placeholder="Correo" asp-for="Correo" required />
                    <input class="form-control mb-2" type="text" placeholder="Telefono" asp-for="Telefono" required />
                    <input class="form-control mb-2" type="text" placeholder="Direccion" asp-for="Direccion" required />
                    <div class="d-grid gap-2 mb-3">
                        <button class="btn btn-primary" type="submit">Crear Usuario</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <a asp-controller="Inicio" asp-action="Index">Volver</a>
</div>

Views/Inicio/Editar.cshtml
@model ProyectoEntityFramework.Models.Usuarios

@{
    ViewData["Title"] = "Crear usuario";
}

<div class="text-center">
    <h2 class="display-4">Editar usuarios</h2>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-secondary">
                <p class="text-white">Editar usuario</p>
            </div>
            <div class="card body">
                <form asp-action="Editar" method="post" class="p-2">
                    <!-- Enviando el Id del usuario como un campo oculto-->
                    <input type="hidden" asp-for="IdUsuario"/>

                    <input class="form-control mb-2" type="text" placeholder="Nombre" asp-for="Nombre" required />
                    <input class="form-control mb-2" type="email" placeholder="Correo" asp-for="Correo" required />
                    <input class="form-control mb-2" type="text" placeholder="Telefono" asp-for="Telefono" required />
                    <input class="form-control mb-2" type="text" placeholder="Direccion" asp-for="Direccion" required />
                    <div class="d-grid gap-2 mb-3">
                        <button class="btn btn-primary" type="submit">Editar Usuario</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <a asp-controller="Inicio" asp-action="Index">Volver</a>
</div>

Views/Inicio/Eliminar.cshtml
@model ProyectoEntityFramework.Models.Usuarios

@{
    ViewData["Title"] = "Eliminar usuarios";
}

<div class="text-center">
    <h2 class="display-4">Eliminar usuario</h2>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-secondary">
                <p class="text-white">Eliminar usuario</p>
            </div>
            <div class="card body">
                <form asp-action="Eliminar" class="p-2">
                    <!-- Enviando el Id del usuario como un campo oculto-->
                    <input type="hidden" asp-for="IdUsuario" />

                    <input class="form-control mb-2" type="text" asp-for="Nombre" readonly />
                    <input class="form-control mb-2" type="email" asp-for="Correo" readonly />
                    <input class="form-control mb-2" type="text" asp-for="Telefono" readonly />
                    <input class="form-control mb-2" type="text" asp-for="Direccion" readonly />
                    <div class="d-grid gap-2 mb-3">
                        <button class="btn btn-primary" type="submit">Confirmar eliminación de este Usuario</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <a asp-controller="Inicio" asp-action="Index">Volver</a>
</div>

Views/Inicio/Index.cshtml
@model IEnumerable<ProyectoEntityFramework.Models.Usuarios>

@{
    ViewData["Title"] = "Lista de usuarios";
}

<div class="text-center">
    <h2 class="display-4">Lista de usuarios</h2>
</div>
<div class="row">
    <div class="offset-12 mb-3">
        <a asp-action="Crear" asp-asp-controller="Inicio" class="btn btn-primary text-white">Crear Usuario</a>
    </div>    
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-secondary">
                <p class="text-white">Lista de usuarios</p>
            </div>
            <div class="card body">
                <div class="table">
                    @if (Model.Count() > 0)
                    {
                        <table class="table" id="tableUsuario" width="100%" cellspacing="0">
                            <thead class="table-light">
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.IdUsuario)</th>
                                    <th>@Html.DisplayNameFor(model => model.Nombre)</th>
                                    <th>@Html.DisplayNameFor(model => model.Correo)</th>
                                    <th>@Html.DisplayNameFor(model => model.Telefono)</th>
                                    <th>@Html.DisplayNameFor(model => model.Direccion)</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(model => item.IdUsuario)</td>
                                        <td>@Html.DisplayFor(model => item.Nombre)</td>
                                        <td>@Html.DisplayFor(model => item.Correo)</td>
                                        <td>@Html.DisplayFor(model => item.Telefono)</td>
                                        <td>@Html.DisplayFor(model => item.Direccion)</td>
                                        <td>
                                            <a asp-action="Editar" asp-route-id="@item.IdUsuario">Editar</a>
                                            <a asp-action="Eliminar" asp-route-id="@item.IdUsuario">Eliminar</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <p>Aún no hay usuarios registrados.</p>
                    }
                </div>
            </div>
        </div>
    </div> 
</div>

                                            

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoEntityFramework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoEntityFramework.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Inicio" asp-action="Index">ProyectoEntityFramework</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inicio" asp-action="Index">Inicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProyectoEntityFramework - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>